### PR TITLE
Save system feature

### PR DESCRIPTION
**Pull request by SimeonTsekov**

### CODE REVIEW

**Comment by KirilChingarov** [comment]
Why did you overwrite the TakeDamage() function in the PlayerHealth.cs. Can't you just write the playerHealth variable in the GameStateController every time the player takes damage.

**Comment by SimeonTsekov** [comment]
There are two reasons. Since the playerHealth is part of the state of the game, it is more logical that it is changed within the GameStateController. Second reason is that this way the script is made more universal and can be used outside of playerHealth class without needing new instances.

**Comment by KirilChingarov** [comment]
The problem is that it only subtracts from the playerHealth variable. Why don't you make the function get playerHealth variable instead of taking damage, and we will implement it in other scripts.

**Comment by SimeonTsekov** [comment]
I returned the health subtraction to the playerHealth script and left the health in the GameStateController public for future interactions.

**Review by KirilChingarov — APPROVED** [review]
LGTM

**Pull request merged**
